### ISSUE TITLE
Invalid value: Valid value range is empty when using ShowUpList

### ISSUE THREAD

**Issue by MostafaSolimanMO** [thecodepapaya/show_up_animation#7]
When I tried to use `ShowUpList` with `enableLazyLoading` is `false`
It throw `RangeError (index): Invalid value: Valid value range is empty: 0`

**Comment by SIHU08** [comment]
#9 
I modified it. Please use this version.
```yaml
dependencies:
  show_up_animation:
    git:
      url: https://github.com/SIHU08/show_up_animation.git
```
